apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ilead
  description: ilead.com
  annotations:
    ilead.io/project-name: employee
    ilead.io/program-name: employeeprogram
    github.com/project-slug: test
spec:
  type: service
  lifecycle: production
  owner: user:ambrish
catalog:
  locations:
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/docs-template/template.yaml
      rules:
        - allow: [Template]
